# Book settings
title: Sustainability in High School Mathematics
logo: images/logos/logo.png
author: Lars Quaedvlieg
email: larsquaedvlieg@outlook.com
copyright: "2023"

# Execution settings
execute:
  execute_notebooks: auto  # Must be one of ("auto", "force", "cache", "off")
  allow_errors: false

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
  myst_dmath_double_inline: true

# HTML-specific settings
html:
  favicon: images/logos/favicon.ico
  home_page_in_navbar: true
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  extra_navbar: Project for "HUM-433 How People Learn II" at <a target="_blank" href="https://edu.epfl.ch/coursebook/en/how-people-learn-designing-learning-tools-ii-HUM-433">École Polytechnique Fédérale de Lausanne</a>
  baseurl: "https://lars-quaedvlieg.github.io/Sustainability-High-School-Mathematics/"
  comments:
    hypothesis: true

# LaTeX-specific settings
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true

# Launch button settings
launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"
  thebe: false

repository:
  url: https://github.com/lars-quaedvlieg/Sustainability-High-School-Mathematics
  path_to_book: docs
  branch: master

# References settings
bibtex_bibfiles:
  - references.bib

# Advanced settings
sphinx:
  extra_extensions:
    - sphinx_design
    - sphinx_proof
    - sphinxcontrib.pseudocode
  config:
    language: en
    panels_add_fontawesome_latex: true
    html_js_files:
      - https://kit.fontawesome.com/26eda3309b.js
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js